### ISSUE TITLE
Reservation suggestion: adaptive audio

### ISSUE THREAD

**Issue by CAD97** [bevyengine/bevy-crate-reservations#17]
[FMOD](https://www.fmod.com/) and [Wwise](https://www.audiokinetic.com/en/products/wwise) are the two leading engines for adaptive/interactive audio in games. In addition to being a traditional audio library, they offer tooling that integrates into the engine to provide a specialized DAW-like editor for reactive audio implementation, including live updates of the audio scripts while the game is running.

(For a nice overview / FMOD ad, see [this video](https://youtu.be/p-FLWabby4Y).)

Given the prominence of both FMOD and Wwise, it seems wise to add `bevy_fmod` and `bevy_wwise` to the list of officially reserved names, alongside the other reserved integration names (e.g. box2d, imgui). FMOD/Wwise aren't free software (and a pure Rust adaptive audio runtime solution would be amazing[^1]), but the integration reservation still seems reasonable.

(I'm currently working on an FMOD binding with the intent of implementing a bevy plugin, ideally as bevy_fmod.)

[^1]: Once I have bevy_fmod working... this might be my dream project. Adaptive audio is basically the center of the Venn diagram of my interests, so maybe I could try to tackle it in the future.

**Comment by cart** [comment]
I'm convinced. Reserved!
