### ISSUE TITLE
Reserve bevy_extension

### ISSUE THREAD

**Issue by JonahPlusPlus** [bevyengine/bevy-crate-reservations#20]
There has been some discussion of a bevy editor, and I'm in favor for using DLLs (dll/so/dylib) for loading extensions at runtime. I think reserving this crate is just prudent for whatever path is taken for extensions (I think if DLLs are used it could be used for macros that take care of things like function signatures or defining common types for extensions).

**Comment by cart** [comment]
Good call. Done!
