### ISSUE TITLE
Reserve bevy_wasm

### ISSUE THREAD

**Issue by afonsolage** [bevyengine/bevy-crate-reservations#22]
Since `bevy` supports `wasm32-unknown-unknown` and `bevy` likely will have (maybe?) editor/game modding in the future, it would be a good ideia to reserve a crate name to deal with it.

**Comment by cart** [comment]
Wow I completely overlooked this. Definitely a good idea. And sadly too late now: https://crates.io/crates/bevy_wasm
This was definitely my bad!
