### ISSUE TITLE
Additional crate names

### ISSUE THREAD

**Issue by Telzhaak** [bevyengine/bevy-crate-reservations#6]
For later stages of engine development a crate to handle projects over multiple devs in sync would be useful for managing and collaboration. Keeping it seperate from bevy_editor might improve maintainability
- bevy_project

a generic crate for everything that has not ONE place to be in, similar to bevy_utils, a collection/parent-crate of misc self-written or re-exported algorithms
- bevy_algorithms

Similar to Unity or UE4 (not even necessarily for bevy-monetization, but for creators using bevy)
- bevy_marketplace
- bevy_store

**Comment by cart** [comment]
Good ideas! I just reserved bevy_project, bevy_marketplace, and bevy_store. bevy_algorithms is pretty generic. I wouldn't feel bad losing it as a name option, so I've left that out for now.
