### ISSUE TITLE
Reserve bevy_cli

### ISSUE THREAD

**Issue by DJMcNab** [bevyengine/bevy-crate-reservations#7]
https://github.com/bevyengine/bevy/issues/436

In theory, a minimum viable version of the cli would be one which simply calls out to external binaries of the form `bevy_<subcommand>`. For example, I could forsee a `bevy_web` subcommand which does all of the web stuff.

However, making that happen is development effort, so simply reserving it here is good enough for now.

**Comment by cart** [comment]
Good call. Done!
